---
title: "Report"
author: ""
date: ""
output: pdf_document
---

```{r setup, include=FALSE}
  knitr::opts_chunk$set(echo = TRUE)
  rm(list = ls())
  graphics.off()
  library(tibble)
  library(ggplot2)
  setwd(getwd())
```

```{r, include=FALSE}
  source("variables.R",local = knitr::knit_global())
```

This report represents a statistical analysis of the main thermodynamic variables. The figures below show the time evolution of energy, temperature, pressure and volume. The red lines are the linear regression of the values.

## Energy

```{r df, echo=FALSE}
  df %>% ggplot(aes(x=V1,y=V2))+
  geom_line(color="black")+
  geom_smooth(method = "lm",color="red")+
  theme_bw()+theme(panel.grid = element_blank())+
  labs(x="Time (ps)",y=expression(paste("Volume ",(ring(A)^3))))
```

Here is the statistical values

```{r df$V2, echo=FALSE}
  summary(df$V2)
```

## Temperature

```{r df, echo=FALSE}
  df %>% ggplot(aes(x=V1,y=V3))+
  geom_line(color="black")+
  geom_smooth(method = "lm",color="red")+
  theme_bw()+theme(panel.grid = element_blank())+
  labs(x="Time (ps)",y=expression(paste("Temperature (K)")))
```

Here is the statistical values

```{r df$V3, echo=FALSE}
  summary(df$V3)
```

