---
title: "Report"
author: ""
date: ""
output: pdf_document
---

```{r setup, include=FALSE}
  knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
  rm(list = ls())
  graphics.off()
  library(tidyverse)
  setwd(getwd())
```

```{r, include=FALSE}
  source("import_and_clean_data.R",local = knitr::knit_global())
```

This report represents a statistical analysis of the main thermodynamic variables. The figures below show the time evolution of Volume, temperature, pressure and density followed by the linear regression (red line).

## Parameters

```{r, echo=FALSE}
  print.simple.list(df$V2,quote=FALSE)
```

## Volume

```{r, echo=FALSE}
  df2 %>%
  filter(data=='VOLUME') %>%
    ggplot(aes(x=TIME,y=Value))+
    geom_line(color="black")+
    geom_smooth(color="red",se=T)+
    labs(x="Time (ps)",y=expression(paste("Volume ",(ring(A)^3))))
```

## Temperature

```{r, echo=FALSE}
  df2 %>%
  filter(data=='TEMPERATURE') %>%
    ggplot(aes(x=TIME,y=Value))+
    geom_line(color="black")+
    geom_smooth(color="red",se=T)+
    labs(x="Time (ps)",y=expression(paste("Temperature (K)")))
```

## Pressure

```{r, echo=FALSE}
  df2 %>%
  filter(data=='PRESSURE') %>%
    ggplot(aes(x=TIME,y=Value))+
    geom_line(color="black")+
    geom_smooth(color="red",se=T)+
    labs(x="Time (ps)",y=expression(paste("Pressure (atm)")))
```

```{r summary, echo=FALSE}
  df2 %>%
  filter(data=='ENERGY') %>%
  ggplot(aes(x=TIME,y=Value))+
  geom_line(color="black")+
  geom_smooth(color="red",se=T)+
  labs(x="Time (ps)",y=expression(paste("Energy (kcal/mol)")))
```

# Gathering thermodynamic values.

```{r, echo=FALSE}
  ggplot()+
    geom_line(data=filter(df2,data=='VOLUME'),mapping=aes(x=TIME,y=Value),color="black")+
    geom_smooth(data=filter(df2,data=='VOLUME'),mapping=aes(x=TIME,y=Value),color="red",se=T)+
    geom_line(data=filter(df2,data=='TEMPERATURE'),mapping=aes(x=TIME,y=Value),color="black")+
    geom_smooth(data=filter(df2,data=='TEMPERATURE'),mapping=aes(x=TIME,y=Value),color="red",se=T)+
    geom_line(data=filter(df2,data=='PRESSURE'),mapping=aes(x=TIME,y=Value),color="black")+
    geom_smooth(data=filter(df2,data=='PRESSURE'),mapping=aes(x=TIME,y=Value),color="red",se=T)+     geom_line(data=filter(df2,data=='ENERGY'),mapping=aes(x=TIME,y=Value),color="black")+
    geom_smooth(data=filter(df2,data=='ENERGY'),mapping=aes(x=TIME,y=Value),color="red",se=T)+
  facet_wrap(~data,nrow = 2,scales = 'free')
```

# Here is the summary of some thermodynamic variables.

```{r FIT_ENERGY, echo=FALSE}
  df2 %>%
  spread(key="data",value="Value") %>%
  select(VOLUME:ENERGY) %>%
  summary()
```
